tickers:
  - TQQQ
  - SOXL
  - LABU
  - FNGU
  - TECL
  - SPXL
  - UVXY
  - SQQQ
  - SOXS
  - SPXS

top_n: 4
per_trade_budget: 300        # smaller sizing; these move fast
stop_atr_mult: 2.8           # wider stops for leveraged vol
take_atr_mult: 5.0
atr_lookback: 14

hold:
  enabled: false             # recommend OFF for leveraged ETFs initially
  skip_friday: true
  max_overnight_positions: 0
  max_overnight_notional: 0
  min_today_ret: 0.005
  require_sma_trend: true
  stop_atr_mult: 1.8
  atr_lookback: 14      # take = close + 2.0 * ATR

# Behavior
dry_run: true                # true = print orders only; set false to really trade
time_zone: "America/New_York"  # market reference
