name: Friday Summary

on:
  schedule:
    - cron: "15 21 * * 5"   # Fridays ~5:15 PM ET (21:15 UTC)
  workflow_dispatch: {}

jobs:
  weekly:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run weekly summary
        run: python weekly_summary.py
